name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew build
      - name: Property file check Test
        run: java -cp build/libs/*.jar com.github.horitaku1124.cli_validator.PropertyValidate2Kt src/main/resource/test1.properties
      - name: HTML file check Test
        run: java -cp build/libs/*.jar com.github.horitaku1124.cli_validator.HtmlValidateKt src/main/resource/test1.html